name: Deploy Laravel to EC2

on:
  push:
    branches: [ main ]  # Ou master, dependendo do nome da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up job
      uses: actions/checkout@v3
      
    - name: Checkout código
      run: |
        echo "Verificando código..."
        # Se você precisar fazer alguma verificação adicional, coloque aqui
        
    - name: Configurar SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}
        
    - name: Adicionar known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        
    - name: Enviar código para EC2
      run: |
        # Instalar dependências do composer primeiro
        composer install --no-interaction --prefer-dist --optimize-autoloader
        
        # Compilar assets se estiver usando npm/yarn
        # npm ci
        # npm run build
        
        # Deploy usando rsync com sudo
        rsync -avz --delete \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='node_modules' \
          --exclude='.env.example' \
          ./ "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/coloque-o-nome-do-seu-projecto-aqui/" \
          --rsync-path="sudo rsync"
          
    - name: Configurar Laravel no servidor
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /var/www/html/meu-amor
          sudo chown -R apache:apache .
          sudo chmod -R 775 .
          sudo chmod -R 775 storage bootstrap/cache
          
           # Criar .env com variáveis sensíveis
          cat <<EOF | sudo tee .env > /dev/null
          APP_NAME=Laravel
          APP_ENV=production
          APP_KEY=
          APP_DEBUG=true
          APP_URL=https://meuamor.xyz

          LOG_CHANNEL=stack

          DB_CONNECTION=mysql
          DB_HOST=127.0.0.1
          DB_PORT=3306
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}

          CACHE_DRIVER=file
          QUEUE_CONNECTION=sync
          SESSION_DRIVER=file
          SESSION_LIFETIME=120
          EOF

          # Gerar nova chave
          sudo php artisan key:generate --force

          # Rodar migrations
          sudo php artisan migrate --force
          sudo php artisan storage:link
          
          # Configurar Laravel
          sudo php artisan config:cache
          sudo php artisan route:cache
          sudo php artisan view:cache
          sudo php artisan optimize
          
          # Reiniciar o Apache
          sudo systemctl restart httpd
